language: csharp
solution: ./ConsoleApplication1/ConsoleApplication1.sln
install:
- sudo apt-get install -y gtk-sharp2
- nuget restore ./ConsoleApplication1/ConsoleApplication1.sln
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild /p:Configuration=Release ./ConsoleApplication1/ConsoleApplication1.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ConsoleApplication1/Tests/bin/Release/Tests.dll