language: csharp
solution: ./ConsoleApplication1/ConsoleApplication1.sln
install:
- sudo apt-get install -y gtk-sharp2
- nuget restore ./ConsoleApplication1/ConsoleApplication1.sln
script:
- xbuild /p:Configuration=Release ./ConsoleApplication1/ConsoleApplication1.sln
- mono ./testrunner/NUnit.Runners.3.5.0/tools/nunit-console.exe ./ConsoleApplication1/Tests/Release/Tests.dll